name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "stage1 step"

   stage2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "stage2 step"
